### ISSUE TITLE
fs-extra doesn't seem to be exporting an rmSync method as native nodejs fs module does 

### ISSUE THREAD

**Issue by rpl** [saadtazi/firefox-profile-js#128]
While running [web-ext](https://github.com/mozilla/web-ext) unit tests locally I did notice the following error being logged when mocha did run all tests and it is exiting:
```
[firefox-profile] cannot delete profileDir on exit /tmp/firefox-profile2Tntmz/ TypeError: fs.rmSync is not a function
    at FirefoxProfile._cleanOnExit (/.../web-ext/node_modules/firefox-profile/lib/firefox_profile.js:288:10)
    at process.FirefoxProfile.onExit (/.../web-ext/node_modules/firefox-profile/lib/firefox_profile.js:170:12)
    at process.emit (events.js:326:22)
    at process.EventEmitter.emit (domain.js:483:12)
    at process.emit (/.../web-ext/node_modules/addons-linter/node_modules/source-map-support/source-map-support.js:516:21)
    at process.emit (/.../web-ext/node_modules/source-map-support/source-map-support.js:516:21)
    at process.topLevelDomainCallback (domain.js:138:15)
    at process.callbackTrampoline (internal/async_hooks.js:124:14)
```

As the stack trace shows the error seems to be related to the changes introduced in #126 and released on npm as part of firefox-profile@4.2.1.

Based on a very quick look I think that the exception is actually expected, because `fs` is actually set to the `"fs-extra"` here:
- https://github.com/saadtazi/firefox-profile-js/blob/f77a86fa62328e76d18bb9b4741c7d5f5e9151d5/lib/firefox_profile.js#L9

and `rmSync` doesn't seem to be part of the API exposed by "fs-extra" npm package (where it seems that only `removeSync` is actually available), unlike the native nodejs `"fs"` module which does actually have [an `rmSync` method with that signature](https://nodejs.org/api/fs.html#fsrmsyncpath-options).

Looking more closely to the fs-extra removeSync function (which was also what that method used to call before #126), it seems that it should be already calling fs.rmSync internally on nodejs version where it is actually available:
- https://github.com/jprichardson/node-fs-extra/blob/a84ef6dd8969f57d16e23267e1790def791e9a82/lib/remove/index.js#L13-L17

And so it seems that rolling back to the previous implementation (the one already being calling fs-extra removeSync) may be actually a reasonable fix for this issue and should still remove that directory as the new version was meant to ensure.

**Comment by saadtazi** [comment]
Wow! Thank you so much for the detailed explanations.

You are probably using a node version < 14.4, which doesn't support `fs.rmSync`

note: fs-extra contains the methods of the regular `fs` module plus some extra functions. So the change introduced by #126 only worked for node 14.4+...

I'm finalizing a PR to fix it. please stay tuned 😄

**Comment by saadtazi** [comment]
I am waiting for travis-ci to grant me open-source credits: they closed `travis-ci.org` "recently" and the switch to `travis-ci.com` for open-source projects requires some communications/manual approvals with their support team...

**Comment by saadtazi** [comment]
I just released v4.2.2. Please let me know if it fixes your issue.

**Comment by rpl** [comment]
> Wow! Thank you so much for the detailed explanations.
> 
> You are probably using a node version < 14.4, which doesn't support `fs.rmSync`
> 
> note: fs-extra contains the methods of the regular `fs` module plus some extra functions. So the change introduced by #126 only worked for node 14.4+...

That was it! 
I use mainly the last node 12 while working on [web-ext](https://github.com/mozilla/web-ext) (as it is the minimum nodejs version still supported by `web-ext` package).

> I just released v4.2.2. Please let me know if it fixes your issue.

I just tested locally the related Renovate bot PR (mozilla/web-ext#2344) and I can confirm you that the issue is fixed by v4.2.2 :tada: 

Thanks a lot! :heart:
